- README.md
Remove trailing space and add new solutions with Rust and TS.
> Add new solutions

- README.md
Solution is using Golang primarily.
> new solution for wc challenge added

- README.md
Added a shared solution for word count challenge which is written in python and using click cli module
> Add shared solution for wc challenge in python

- README.md
ccwc counts various statistics of a text file, such as the number of lines, words, characters, and bytes. It takes command-line arguments to specify the operation and the file to be analyzed.
> Write Your Own wc Tool C++ solution

- README.md
> Add rate limiter NodeJS solutions

- README.md
Ruby solution for wc tool challenge
> wc tool challenge

- README.md
Description:
1. Updated the readme file to include another solution of DNS resolver.
> Add solution of DNS resolver

- README.md
Added the cat tool challanges solution link
> Added cat command challenge solution link 

- README.md
Shared solution to Build your own URL Shortener challenge - https://github.com/jengori/short-changed
> share solution to Build your own URL Shortener challenge

- README.md
I have implemented many coding challenges in Java. I added them all to the list
> Update README.md with lolo8304 coding challenges

- README.md
The JSON Parser does the parsing and validation of data in a format resembling JSON. It starts by breaking down the input data into individual tokens through lexical analysis. Then, it proceeds to parse and validate the data structure, ensuring that it conforms to the expected JSON-like format. It ultimately determines whether the input data is "VALID JSON" or "INVALID JSON" based on the correctness of its structure.
> Write Your Own JSON Parser C++ solution

- README.md
Challenge 29 - Scheduling automation app
> Challenge 29 - Scheduling Automation App

- README.md
Added link to Rate limiter challenge in Node.JS and Typescript
> Update README.md - Rate limiter challenge

- README.md
gauravguptadeveloper: wc tool link added
> WC-Tool Link added

- README.md
I've added my solutions in C# for wc tool and the JSON parser.
> Update README.md and added wc and jsonparser

- README.md
I have added Python solution to the URL Shortner challenge. Please consider this for shared solution.
> Update README.md and added URL Shortener to Shared solutions

- README.md
Add Build Your Own Calculator solution - https://github.com/jengori/Calcu-Llama)
> Add Build Your Own Calculator solution

- README.md
Solving this challenge with nice use of go's switch statement.
```
switch {
case *charFlag: 
output += fmt.Sprintf("%d ", CalculateNoOfChars(fileData))
case *lineFlag:
output += fmt.Sprintf("%d ", CalculateNoOfLines(fileData))
case * wordFlag:
output += fmt.Sprintf("%d ", CalculateNoOfWords(fileData))
case *byteFlag:
output += fmt.Sprintf("%d ", CalculateNoOfBytes(fileData))
default:
output += fmt.Sprintf("%d %d %d ", CalculateNoOfLines(fileData), CalculateNoOfWords(fileData), CalculateNoOfBytes(fileData))
}
```
> wc go solution

- README.md
I'm excited to contribute to this project by sharing my solution for the "Write your X" challenge. As part of the challenge, I have developed a full-stack URL shortener web application. This application is not only a coding challenge solution but is also deployed and live for everyone to test and use.
[URL Shortener Repo](https://github.com/abhijeetnishal/URLShortener)
You can check out the live demo of my web application here: [Live Demo](https://urlsrtner.vercel.app/)
> Added solution for URL Shortener Challenge

- README.md
> Added wc python solution

- README.md
I'm excited to contribute to this project by sharing my solution for the "Write your X" challenge. I have implemented rate limiter as one of the coding challenges.
[Rate Limiter Repo](https://github.com/abhijeetnishal/Build-Your-Own-X/tree/master/rate-limiter)
> Added Rate limiter solution

- README.md
Add solution for creating wc tool written in python
> Add solution for wc-tool in python

- README.md
added solution link: https://gitlab.com/surshrestha/rate-limiters
> added ratelimiter python solution

- README.md
- Added repository for word count challenge.
> challenge 1 updated

- README.md
Added  wc tool challenge solution in go
> Added wc tool challenge solution

- README.md
I'm excited to contribute to this project by sharing my solution for the "Build your X" challenge. I have implemented Load Balancer as one of the coding challenges.
Link to my repository:
[Load Balancer Repo](https://github.com/abhijeetnishal/Build-Your-Own-X/tree/master/load-balancer)
> Added Load Balancer solution

- README.md
Added to list of solutions for Build Your Own JSON Parser Coding Challenge - https://github.com/jengori/json_parser
> Add solution to Build Your Own JSON Parser

- README.md
Added "Back to Top" button in the Readme.md file.
Closes: #50 
**Description**
As the readme.md is very huge and log this button will help the users to scroll to top in just one click .
**Screenshot**
> Add "Back to Top" in Readme.md

- README.md
Hi John, I have added my solution link to the readme file.
> Solution for challenge 33: build your own head

- README.md
I have added the link to my load-balancer project
> adding-load-balancer-project

- README.md
- Added a link to join the discord community
> added the discord link to the Readme.md

- README.md
Building JSON-parser from scratch using JS
> First JSON-parser project

- Solutions/challenge-huffman.md
The Huffman compression and decompression utility designed to efficiently compress and decompress text data. It performs the compression and decompression of files using the Huffman coding algorithm, a popular method for data compression.
> Write Your Own Compression Tool C++ solution

- Solutions/challenge-lisp.md
> Update challenge-lisp.md. Adding a new solution for 'Write Your Own Lisp Interpreter'

- README.md
- Solutions/challenge-qr-generator.md
And my full solution of QR code generator in Java
> Added QR code generator 

- Solutions/challenge-wc.md
Added a simple solutions for wc-tool in JavaScript
> add js solution to wc tool challenge

- README.md
- Solutions/challenge-pong.md
Add challenge-pong.md and my solution to the challenge.
> Add challenge-pong.md

- Solutions/challenge-realtime-chat.md
Add solution to realtime-chat challenge using pure Ruby
> Add ruby solution to realtime-chat challenge 

- Solutions/challenge-diff.md
- Solutions/challenge-load-balancer.md
- Solutions/challenge-rate-limiter.md
- Solutions/challenge-redis.md
- Solutions/challenge-wc.md
Adding Golang solutions for these coding challenges -
1. Rate limiter
2. Load balancer
3. Diff tool
4. wc tool
> Solutions in Golang - vamsaty

- Solutions/challenge-wc.md
There was a spelling mistake in the `Write Your Own wc Tool` MDX file.
> [MDX] Spelling mistake in "Write Your Own wc Tool"

- README.md
Fix: [#106](https://github.com/CodingChallegesFYI/SharedSolutions/issues/106)
> fix: organized the ToC

- Solutions/challenge-wc.md
Adding my go solution to the WC coding challenge
> Add carantes solution to wc challenge

- Solutions/challenge-wc.md
Golang solution for wc challange
> [abhi11210646] Add wc-tool solution

- Solutions/challenge-wc.md
I had a lot of fun doing this challenge in a new language (Go). I have also documented the learning, so a beginner like me would find it useful.
> Adding Vignesh's wctool solution

- Solutions/challenge-wc.md
This challenge is to build your own version of the Unix command line tool wc!
> added my challenge-wc solution

- Solutions/challenge-redis.md
Added new solution to Write Your Own Redis challenge in Java prog lang
> Added new solution to Write Your Own Redis challenge in Java prog lang

- Solutions/challenge-rate-limiter.md
- Adding Java/Spring solution to Rate Limiter Challange.
- Row numbers fixed.
> feat: adding Java solution to challenge-rate-limiter.md

- Solutions/challenge-url-shortener.md
add solution for url-shortener using ruby on rails
> add solution for url-shortener using ruby

- Solutions/challenge-curl.md
Added @Sidray-Infinity 's  implementation of curl in python
> [Python] Write your own Curl

- Solutions/challenge-memcached.md
Solution for [Coding Challenges #17 - Memcached Server](https://codingchallenges.substack.com/p/coding-challenge-17-memcached-server)
> Added C++ memcached solution cha-ku/memsaab

- Solutions/challenge-url-shortener.md
removed auto formatting from the previous pull req.
> Add jmadupalli/shortly - URL Shortener

- Solutions/challenge-wc.md
adding wcTool solution, written in Go, by Trevor Arnold
> adding wcTool solution, written in Go, by Trevor Arnold

- Solutions/challenge-load-tester.md
Added my solution to the challenge-load-tester.md file.
> Added load tester challenge rojasjo solution

- Solutions/challenge-wc.md
> Add wc solution in JavaScript

- Solutions/challenge-wc.md
I wrote it in **Go**
[Screencast from 14-01-24 13:51:58.webm](https://github.com/CodingChallegesFYI/SharedSolutions/assets/67675749/3d7a366a-2506-4a36-b5eb-f7a2d4d83122)
> Add wc solutions in Go

- Solutions/challenge-wc.md
https://github.com/CodingChallegesFYI/SharedSolutions/assets/22665788/e8c8020b-bfd7-4800-8a7e-77152629d0bf
> Add go solution to challenge-wc.md.

- Solutions/challenge-url-shortener.md
Hi John!
Thanks for the ideas you've been given in the coding challenges. This is the URL shortener challenge solution i've told you over linkedin. Looking forward to share other solutions in here.
Best,
Erick Grilo.
> added https://github.com/simasgrilo/urlshortener as a shared solution for the URL shortener challenge

- Solutions/challenge-webserver.md
> adding webserver challenge

- Solutions/challenge-pong.md
Hi john I've added my solution of pong-game
> adding pong game

- Solutions/challenge-wc.md
Added WC solution for codingchallenges.fyi solutions collection.
> Submitted WC solution for codingchallenges.fyi

- Solutions/challenge-head.md
- Solutions/challenge-wc.md
adding Luke Carani head solution to shared solutions repo.
> Submitted head solution for codingchallenges.fyi

- Solutions/challenge-json-parser.md
Hi john, here's my solution to the challenge "create your own JSON parser"
> adding JSON parser challenge

- Solutions/challenge-shell.md
armshell is an implementation of a shell written in c
> added armshell

- Solutions/challenge-load-tester.md
- Solutions/challenge-portscanner.md
- Add a link to port scanner challenge
- Add a link to http load tester challenge
> Add link to challenges

- Solutions/challenge-webserver.md
A basic HTTP server using Multi-processing, Multi-threading and Coroutines (asyncio)
Author: agparv19@gmail.com
> Add webserver solution

- Solutions/challenge-json-parser.md
Solution for JSON Parser challenge, written in Raku programming language
> JSON Parser in Raku

- Solutions/challenge-uniq.md
adding uniq tool from Trevor Arnold
> adding uniq tool from Trevor Arnold

- Solutions/challenge-json-parser.md
Added the solution for json-parser in Java. Completed the challenge in Java using the inbuilt Deque data structure for the LIFO operations. 
> Adding solution for json-parser in Java

- Solutions/challenge-cat.md
Python Solution for the build your own cat-tool by JayUnitTest
> Added solution for BYO: cat-tool - python

- Solutions/challenge-cat.md
Recently I completed cat-tool challenge and now linked in challenge-cat.md file.
> Add Solution for Cat-tool

- Solutions/challenge-tetris.md
Added my solution to the Build Your Own Tetris Challenge
> Jen Gori - Tetris Solution

- Solutions/challenge-wc.md
> new wc solution

- Solutions/challenge-wc.md
Added a solution to wc-coding challenges in Javascript.
> Added a solution to wc_tool in Js

- Solutions/challenge-wc.md
Added Perl and Lua solutions for wc
> Perl and Lua solutions for wc

- Solutions/challenge-huffman.md
This PR is a Kotlin implementation of Huffman encoder/decoder problem described in coding challenge _"Build Your Own Compression Tool"_. The code tries to be as simple and clean as possible with comments to better describe the reasoning behind some implementation details and choices.
> Huffman encoder/decoder solution

- Solutions/challenge-discord.md
created go version of discord bot
> created go version of discord bot

- README.md
- Solutions/challenge-data-privacy-vault.md
Hello,
I have added a markdown file for Data Privacy Vault challenge and added my solution to it. Please review.
> Added a solution for data privacy vault

- Solutions/challenge-wc.md
> feat: Add my golang sol of ccwc

- README.md
- Solutions/challenge-password-cracker.md
I modified <https://github.com/clu8/RainbowTable> to generate rainbow tables with multiprocessing.
Also added demonstrations of Key Derivation Functions (KDFs) like Scrypt, Argon2id, and [Balloon](https://en.wikipedia.org/wiki/Balloon_hashing).
> Add Password Cracker challenge solution

- Solutions/challenge-cat.md
Adding my cat solution to the list.
> Add Cat Tool Solution in Java

- Solutions/challenge-chrome-extension.md
Adding my Chrome Extension solution to the list.
> Add my Chrome Extension sol

- Solutions/challenge-webserver.md
Add a Rust implementation for the coding challenge "Build Your Own Web Server" by neutrinoks.
> feat: add neutrinoks solution, web-server

- Solutions/challenge-wc.md
A cw challenge solution in Python.
> Add ccwc challenge solution by marek-jakub.

- Solutions/challenge-crontab.md
added crontab tool from Trevor Arnold
> added crontab tool from Trevor Arnold

- Solutions/challenge-url-shortener.md
Added my project link for the url-shortener project.
> Add my url-shortener project link

- Solutions/challenge-url-shortener.md
Purpose - This PR is being filed to provide solution to the coding challenge by John Crickett viz URL Shortener.
> Coding Challenge | URL Shortener | Solution in Python

- Solutions/challenge-wc.md
Coding Challenge: Build Your Own wc Tool
Change: Add GitHub repository link in challenge-wc.md file
> Update MD File to add Bash Solution for wc Tool

- Solutions/challenge-json-parser.md
Successfully created my own JSON Parser. Added solution link.
> Added solution for Json parser.

- Solutions/challenge-url-shortener.md
Coding Challenge: Build your own URL Shortener
Change: Add GitHub repository link in challenge-url-shortner.md file
> Update MD file to add GitHub repository link

- Solutions/challenge-url-shortener.md
Adds a Rust solution for the backend part of the build your own URL shortener coding challenge.
> Add solution to build your own url shortener

- Solutions/challenge-xxd.md
Since the markdown file wasn't there yet John I created it and added my solution with the rest of the info taken from other similar files.
Thanks!
> added file Solutions/challenge-xxd.md and included link to my solution

- Solutions/challenge-bloom-filter-spell-checker.md
You can try out using homebrew
```
brew install omkarph/tap/spellchecker-bloomfilter
spellchecker-bloomfilter some correct and smoe incorrct wrods
```
> Added Golang solution for challenge-bloom-filter-spell-checker

- Solutions/challenge-cat.md
Added my solution, Please verify and merge it
> Update challenge-cat.md - Added CAT solution

- README.md
- Solutions/challenge-xxd.md
Submitted my solution. Kindly review and consider merging it. Thank you!
> Add solution for xxd challenge written in Golang

- README.md
- Solutions/challenge-pastebin.md
> pastebin in java solution

- Solutions/challenge-redis.md
Solution to "Build your own Redis Server" challenge!
> Add Redis in C++ by agparv19

- README.md
- Solutions/challenge-password-manager.md
- Added the solution to [Build your own password manager](https://codingchallenges.fyi/challenges/challenge-password-manager), using NodeJs.
- Updated the home readme too.
> Added the solution to Build your own password manager

- Solutions/challenge-json-parser.md
Dear sir
Kindly accept this pull request to add my JSON parser solution.
Thank you
> JSON parser solution by ahmedsameha1

- Solutions/challenge-bloom-filter-spell-checker.md
Coding challenges solution, implemented in OCaml
> Add solution to bloom filter spell checker to list of solutions

- Solutions/challenge-shell.md
Adding solution for <a href="https://codingchallenges.fyi/challenges/challenge-shell">Build Your Own Shell</a> in Java .
> adding solution for 'Write Your Own Shell' in Java

- README.md
- Solutions/challenge-wheel.md
Adding a solution for: https://codingchallenges.fyi/challenges/challenge-wheel/
Solution repository: https://github.com/hariharanragothaman/challenge-wheel
> Challenge-Wheel Solution: Build Your Own Wheel of Names

- README.md
Added my solution to the space invaders challenge
> Added space invaders solution

- README.md
- Solutions/challenge-tar.md
I limited the scope a little bit. But it seems to work within scope.
> Adding my solution

- Solutions/challenge-dns-resolver.md
- Solutions/challenge-load-balancer.md
- Solutions/challenge-wc.md
Add my Go solutions following TDD.
Articles for the solution:
* https://domenicoluciani.com/2024/01/29/creating-a-word-count-clone-with-golang.html
* https://domenicoluciani.com/2024/02/12/creating-an-application-layer-load-balancer.html
* https://domenicoluciani.com/2024/05/07/create-dns-resolver.html
> Add my DNS Resolver, wc and load balancer solutions

- Solutions/challenge-wc.md
Added my solution written in go. While coding for this challenge, I have probably also found a bug in the original wc running on Darwin x86 where total -L does not sum up the longest line char count for multiple file.
> Added solution to wc coding challenge

- Solutions/challenge-url-shortener.md
Added my new solution. Kindly review and consider merging it. 
Thanks
> New Solution For Url Shortener (Distributed System) Written In C#

- Solutions/challenge-load-balancer.md
Adds fuad load balancer implementation in GO
> Adds fuad load balancer implementation in GO

- Solutions/challenge-redis.md
Adds redis server implementation in typescript
> Adds redis server implementation in typescript

- Solutions/challenge-memcached.md
Hello, hoping I can add my solution for the Memcached client challenge. I would greatly appreciate some feedback on my solution and code as well!
> Add solution memcached cli tool

- Solutions/challenge-dropbox.md
Add my solution. Fix incorrect label on markdown file (spell checker bloom filter --> dropbox challenge)
> Luke Carani adding Dropbox challenge solution (Java)

- Solutions/challenge-huffman.md
Made this in January this year but forgot to add it in.
> Add Python huffman solution

- README.md
- Solutions/challenge-redis-cli.md
It's a golang redis client but not a cli tool, I started out from building redis server [challenge](https://codingchallenges.fyi/challenges/challenge-redis) and decided to build the client for testing it, eventually I stuck with a client and not a server, the closest challenge in the list is building [redis-cli-tool ](https://codingchallenges.fyi/challenges/challenge-redis-cli) 
I understand that it may not quite fit the description of expected solution, so I'm okay closing this PR in this case
> redis client in go

- Solutions/challenge-cat.md
Adds my solution to the cat tool challenge.
> challenge(cat): add andrenbrandao's solution

- Solutions/challenge-lisp.md
Added a solution in Rust for the the Lisp Interpreter challenge
> Rust solution for Lisp Interpreter challenge

- Solutions/challenge-huffman.md
Golang implementation of Huffman encoder-decoder using runes as base token added.
> Update challenge-huffman.md with Golang solution

- README.md
- Solutions/challenge-chess.md
I have implemented the first chess solution based on the challenge in p5.js JavaScript
> Add Chess solution

- Solutions/challenge-huffman.md
- Solutions/challenge-json-parser.md
- Solutions/challenge-wc.md
I have added my solutions to the first 3 challenges. Please review.
> Added solutions to first 3 challenges in Swift

- Solutions/challenge-json-parser.md
JSON Parser coding challenge completion in OCaml using ocamllex and Menhir
> Add OCaml JSON parser solution to list of solutions

- Solutions/challenge-huffman.md
- Solutions/challenge-json-parser.md
- Solutions/challenge-load-balancer.md
- Solutions/challenge-redis.md
- Solutions/challenge-wc.md
- Adds challenge solution for `wc`. 64f56582ed6968451b563485a4c6d0ee4c018b16
- Adds challenge solution for `json-parser`. ea8924ec72a14c823108190df5234502d9e9a7a9
- Adds challenge solution for `huffman`. c7d03da0241270d00c478890e168b4dbb2513f64
- Adds challenge solution for `load-balancer`. 4a7e0805af44de46b0ae80199190ffb1d8eb1cfb
- Adds challenge solution for `redis-server`. b1a545496c8d38e1d2e4812763e7b9644afd2b26
> feat: add some challenge solutions ✨

- Solutions/challenge-sed.md
This is the Java solution for the challenge : ["Build Your Own Sed"](https://codingchallenges.fyi/challenges/challenge-sed)
Java solution : [link](https://github.com/priyapatelsp/Sed_Tool/tree/main)
> Solution for sed tool in java

- Solutions/challenge-cat.md
- Solutions/challenge-huffman.md
- Solutions/challenge-json-parser.md
- Solutions/challenge-load-balancer.md
- Solutions/challenge-rate-limiter.md
- Solutions/challenge-redis.md
In this PR, I have added my solutions for the following challenges in Go
- Load Balancer
- Rate Limiter
- JSON Parser
- Redis Server
- Cat Tool
- Huffman File compression
By - melsonic
> Add: my solutions

- Solutions/challenge-cat.md
Dear sir,
Kindly accept my solution for the cat challenge.
> The cat challenge by Ahmed Sameh

- Solutions/challenge-wc.md
Adding my own solution to the shared solutions
> Updating challenge-wc.md

- Solutions/challenge-wc.md
PR #376 added solution no. 102 on line 111
I added my solution as no. 103 on line 112
> Add ccwc C++ solution

- Solutions/challenge-load-balancer.md
https://github.com/abhi11210646/load-balancer
> Solution for Load-balancer(goLang)

- Solutions/challenge-traceroute.md
Java solution for - <a href= "https://codingchallenges.fyi/challenges/challenge-traceroute">Write Your Own Traceroute</a>
Github - <a href="https://github.com/priyapatelsp/Traceroute">Traceroute</a> 
Author - <a href="https://github.com/priyapatelsp">priyapatelsp</a>
Note:
Also changed the numbering for C++ solution as both (Typescript & c++) were on seq no 1 .
> Traceroute java solution

- Solutions/challenge-load-balancer.md
Added solution to the Load Balancer Implementation
- Challenge link: [codingchallenges.fyi](https://codingchallenges.fyi/challenges/challenge-load-balancer)
- Solution link: [GitHub Repository](https://github.com/r1999-ron/akka-http-load-balancer)
- Blog post: [Medium - Mastering HTTP Load Balancing with Akka Actors and Scala](https://medium.com/@ronaksengupta/mastering-http-load-balancing-with-akka-actors-and-scala-a-comprehensive-guide-46c00def9f33)
> Committing changes for Load Balancer Implementation using Scala

- Solutions/challenge-calculator.md
Added solution to the Build Your Own Calculator in go language
Challenge link: [codingchallenges.fyi](https://codingchallenges.fyi/challenges/challenge-calculator/)
Solution link: [GitHub Repository](https://github.com/siashish/go-calculator)
> Committing changes for Build Your Own Calculator using Go Language

- Solutions/challenge-huffman.md
Added solution to the Build Your Own Compression Tool in C++ language
Challenge link: https://codingchallenges.fyi/challenges/challenge-huffman
Solution link: https://github.com/TheRa4ina/compresstoolcc
> TheRa4ina huffman solution

- Solutions/challenge-wc.md
I added links to the relevant directory in my GitHub repository.
> Added Anthony Nassar's (AbuCarlo) wc implementation to .md

- Solutions/challenge-calculator.md
- Solutions/challenge-url-shortener.md
- Solutions/challenge-xxd.md
This pull request updates the language and phrasing in the challenge-xxd.md file to enhance clarity and readability. The changes ensure that the content is more precise and easier to understand, providing a better experience for users reviewing the challenge instructions.
> Improve language and clarity in challenge-xxd.md

- Solutions/challenge-wc.md
Added a line in the .md file for my solution.
> Add wccpp to shared solutions (wc tool)

- Solutions/challenge-redis.md
Add my solution of the Redis Server in C
> Add implementation of Redis Server in C 

- Solutions/challenge-json-parser.md
- Solutions/challenge-wc.md
Add json parser solution in C#
> Add json parser

- Solutions/challenge-load-tester.md
Challenge : [Build Your Own HTTP(S) Load Tester](https://codingchallenges.fyi/challenges/challenge-load-tester)
Solution : [Golang Https Load Tester](https://github.com/wagiejack/golang-load-tester)
Author : [bitRot](https://github.com/wagiejack)
Steps 1-6 implemented from the official challenge with following features
- Support for all standard HTTP methods (GET, POST, PUT, PATCH, DELETE)
- Batch processing from file input
- Configurable request concurrency and count
> Added Http(s) Load tester implementation in Golang

- Solutions/challenge-realtime-chat.md
Adding Java Solution for :
Challenge : [Build Your Own Realtime Chat Client and Server](https://codingchallenges.fyi/challenges/challenge-realtime-chat)
Solution : [Realtime Chat Client and Server (Java)](https://github.com/priyapatelsp/Realtime-Chat-Client-and-Server)
Author : [priyapatelsp](https://github.com/priyapatelsp)
> Adding java solution for realtimeChatServer

- Solutions/challenge-diff.md
Hello, here is my Python implementation of diff. Please take a look, I will be very glad to receive feedback
> challenge-diff.md

- Solutions/challenge-uniq.md
My solution to "build your own uniq" in TypeScript.
> Add 'uniq' solution

- Solutions/challenge-xxd.md
Add ccxxd cli tool written in C#
> Add ccxxd cli tool

- Solutions/challenge-snake.md
Dear Sir
Kindly accept my solution for the Build Your Own Snake Game challenge.
Thank you
> ccsnake-game by Ahmed Sameh

- Solutions/challenge-wc.md
Add ccwc python solution entry
> Add ccwc python solution

- Solutions/challenge-wc.md
Hi,
I want to participate by sharing my solution for [Build your own WC tools](https://codingchallenges.fyi/challenges/challenge-wc).
Thank you.
> Add ccwc solution with python

- Solutions/challenge-url-shortener.md
Used Java and Spring Boot. Features integration tests using Testcontainers and Rest Assured
> challenge-url-shortener - Java submission

- Solutions/challenge-json-parser.md
this is a python solution for json parse challenge
> add python sol for json parser

- Solutions/challenge-webserver.md
A simple, extensible TCP server implementation. It handles HTTP requests, processes them via worker threads, and sends appropriate responses using predefined route handlers. It supports multiple HTTP methods and content types, ensuring efficient handling of client connections and requests.
> Write Your Own Web Server C++ solution

- Solutions/challenge-sed.md
This an implementation of the "build-your-own-sed" challenge in Go.
> Add Go implementation of Write Your Own Sed to solutions list

- README.md
- Solutions/challenge-brainf_ck.md
Add my solution for the brainf_ch Interpreter and compiler
> Brainf uck solution lolo8304

- Solutions/challenge-url-shortener.md
kindly merge this request to the main
> added url-shortener solution in javascript

- Solutions/challenge-cat.md
> added cat tool soution

- Solutions/challenge-wc.md
My Zig implementation for wc tool, since there is no Zig wc yet!
Sorry I had to cancel the other Pull request
> Zig wc solution

- Solutions/challenge-rate-limiter.md
merge this solution to the main
> adde rate limiter solution

- Solutions/challenge-wc.md
This PR contains the link to the Word Count solution that I have created using Java.
> Updated solution for word count tool

- Solutions/challenge-redis.md
My first project in Zig. Learnt a lot about memory allocations, especially on heap. Had a change of perspective on how I look at programming and learnt lot of core principles like allocating/dealocating memory for key and values Hashmap, Non blocking IO, Event loops and Thread pools.
> Redis Server: My zig implementation

- Solutions/challenge-cut.md
> add python cut tool solution

- Solutions/challenge-git.md
This is an implementation for build-your-own-git in cpp. 
Please merge :)
> git cpp solution

- Solutions/challenge-wc.md
My solution to the `wc` challenge, implemented (twice) in PHP
> Add PHP ccwc

- Solutions/challenge-json-parser.md
Add jsonParser by Mohit singhal
> Add solution to json parser by Mohit singhal

- Solutions/challenge-shell.md
Add implementation for Shell Coding Challenge
Repo / Code Link: https://github.com/Infinage/cpp-experiments/blob/main/cli/csh.cpp
> Add C++ Implementation of Shell

- Solutions/challenge-dropbox.md
- Solutions/challenge-rate-limiter.md
I have added the Dropbox solution. It is only the backend part. merge this to main
> Ridwan dropbox clone

- Solutions/challenge-wc.md
Adds a new entry to `challenge-wc.md`.
> Add Clojure wc solution

- Solutions/challenge-time-zones-converter.md
Add new entry `challenge-time-zones-converter.md`
Consists of simple full stack app written in fastapi and react to convert timezones.
author: @anubhav100rao
coding challenge-link: https://codingchallenges.substack.com/p/coding-challenge-85-time-zone-converter
> Time zones converter app

- Solutions/challenge-shell.md
> add shell solution in java

- Solutions/challenge-cat.md
This commit adds the hyperlinks to source code of solution of MahendraDani for "Build Your Own Cat" coding challenge.
Source Code : https://github.com/MahendraDani/cat
Thanks,
Mahendra
> add cat solution by MahendraDani

- Solutions/challenge-head.md
This commit adds hyperlink to source code of solution of "Build Your Own Head" coding challenge.
Source Code : https://github.com/MahendraDani/head
> add head solution by Mahendra Dani

- Solutions/challenge-git.md
Add solution for Git Client with C++
Challenge link: https://codingchallenges.fyi/challenges/challenge-git/
> Git Client Implementation with C++

- Solutions/challenge-xxd.md
Added new xxd solution written in Go
> added xxd solution in Go

- Solutions/challenge-which
Added a Node solution for [challenge-which](https://codingchallenges.substack.com/p/coding-challenge-93-which)
> Solve challenge-which

- README.md
- Solutions/challenge-cloc.md
Add link to Coding Challenge #92 - LOC Counter solution
> add golang cloc solution

- Solutions/challenge-cloc.md
Add link to Coding Challenge [#92](https://codingchallenges.substack.com/p/coding-challenge-92-loc-counter) - LOC Counter solution
> add python cloc solution

- README.md
- Solutions/challenge-dhcp-client.md
dear John - happy to be part of your coding challenge community since the start.
here is my new solution
br
Lolo
> 1st and new solutions for DHCP client - in java

- Solutions/challenge-forth.md
This is my Java 21 implementation for a simple Forth interpreter.
To parse the Forth code I use the CongoCC Parser Generator.
> My solution on gitlab

- Solutions/challenge-mandelbrot.md
- Solutions/challenge-time-zones-converter.md
finally found the time to document after implementing this months ago. Did also some performance optoimizations. Great challenges - thx John
> sharing Mandelbrot + timezone converter

- Solutions/challenge-wc.md
Hey @JohnCrickett ! I have completed my solution for the wc tool, please do review the same and provide a review for it.
> add ccwc solution in C++ by CagesThrottleUs

- Solutions/challenge-wc.md
My implementation of wc clone in C
> Edited challenge-wc.md
